// cspell:ignore Xpack xpack Dhruv Kaveri Proximo
"use client";

import { FormEvent, useEffect, useState } from "react";

type Role = "customer" | "admin";
type Status = "Placed" | "In progress" | "Completed" | "Cancelled";
type TicketStatus = "Open" | "In progress" | "Resolved" | "Closed";
type Session = { role: Role; name: string; email: string; company?: string };
type Order = { id: string; name: string; customer: string; email: string; created: string; contacts: string; status: Status; schedule: string; notes?: string; report?: boolean };
type Ticket = { id: string; subject: string; customer: string; priority: "Normal" | "High"; status: TicketStatus; message: string; created: string };

const ADMIN_EMAIL = process.env.NEXT_PUBLIC_ADMIN_EMAIL || "admin@xpack.in";
const ADMIN_PASSWORD = process.env.NEXT_PUBLIC_ADMIN_PASSWORD || "XpackAdmin@2026";
const customerSeed: Session = { role: "customer", name: "Dhruv Kumar", email: "customer@xpack.demo", company: "Dhruv Kumar & Co." };
const initialOrders: Order[] = [
  { id: "BR-1048", name: "Monsoon renewal reminder", customer: "Dhruv Kumar & Co.", email: "customer@xpack.demo", created: "Today, 10:42 AM", contacts: "12,450", status: "Placed", schedule: "Start on processing" },
  { id: "BR-1047", name: "Dealer incentive update", customer: "Kaveri Retail Group", email: "ops@kaveriretail.in", created: "Yesterday, 4:18 PM", contacts: "8,200", status: "In progress", schedule: "Jul 18, 10:00 AM" },
  { id: "BR-1046", name: "New product launch", customer: "Dhruv Kumar & Co.", email: "customer@xpack.demo", created: "Jul 13, 2:05 PM", contacts: "24,000", status: "Completed", schedule: "Completed Jul 14", report: true },
  { id: "BR-1045", name: "Payment due alert", customer: "Proximo Finance", email: "team@proximo.in", created: "Jul 10, 9:25 AM", contacts: "3,840", status: "Completed", schedule: "Completed Jul 11", report: true },
];
const initialTickets: Ticket[] = [
  { id: "TK-208", subject: "Help with contact list format", customer: "Dhruv Kumar & Co.", priority: "Normal", status: "Open", message: "Could you confirm the required phone-number column format?", created: "Today, 9:30 AM" },
  { id: "TK-207", subject: "Report metrics clarification", customer: "Kaveri Retail Group", priority: "High", status: "In progress", message: "We need clarity on the delivered and answered values.", created: "Yesterday" },
];

function Icon({ name, size = 18 }: { name: string; size?: number }) {
  const p: Record<string, React.ReactNode> = {
    grid: <><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></>,
    radio: <><rect x="3" y="5" width="18" height="14" rx="2"/><path d="M7 15h.01M11 15h.01M15 15h2M7 9h10"/></>, users: <><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/></>,
    help: <><circle cx="12" cy="12" r="9"/><path d="M9.5 9a2.6 2.6 0 1 1 4.58 1.68c-1.15 1.06-2.08 1.38-2.08 3.32M12 17h.01"/></>, settings: <><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-2.1 2.1-.06-.06A1.7 1.7 0 0 0 15.76 18a1.7 1.7 0 0 0-1 1.54V20h-3v-.46A1.7 1.7 0 0 0 10.76 18a1.7 1.7 0 0 0-1.88.34l-.06.06-2.1-2.1.06-.06A1.7 1.7 0 0 0 7.12 14a1.7 1.7 0 0 0-1.54-1H5.1v-3h.48A1.7 1.7 0 0 0 7.12 9a1.7 1.7 0 0 0-.34-1.88l-.06-.06 2.1-2.1.06.06A1.7 1.7 0 0 0 10.76 5a1.7 1.7 0 0 0 1-1.54V3h3v.46A1.7 1.7 0 0 0 15.76 5a1.7 1.7 0 0 0 1.88-.34l.06-.06 2.1 2.1-.06.06A1.7 1.7 0 0 0 19.4 9a1.7 1.7 0 0 0 1.54 1h.48v3h-.48A1.7 1.7 0 0 0 19.4 15Z"/></>,
    bell: <><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/></>, plus: <><path d="M12 5v14M5 12h14"/></>, chart: <><path d="M4 19V5M4 19h17M8 15v-3M12 15V8M16 15V5M20 15v-7"/></>, clock: <><circle cx="12" cy="12" r="8"/><path d="M12 8v4l3 2"/></>, arrow: <><path d="M5 12h14M13 6l6 6-6 6"/></>, search: <><circle cx="11" cy="11" r="6"/><path d="m20 20-4.2-4.2"/></>, file: <><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8Z"/><path d="M14 2v6h6M8 13h8M8 17h5"/></>, more: <><circle cx="5" cy="12" r="1" fill="currentColor"/><circle cx="12" cy="12" r="1" fill="currentColor"/><circle cx="19" cy="12" r="1" fill="currentColor"/></>, close: <><path d="m6 6 12 12M18 6 6 18"/></>, upload: <><path d="M12 16V4M7 9l5-5 5 5M5 20h14"/></>, activity: <><path d="M3 12h4l2-6 4 12 2-6h6"/></>, check: <><path d="m5 12 4 4L19 6"/></>, lock: <><rect x="4" y="10" width="16" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/></>, logout: <><path d="M10 17l5-5-5-5M15 12H3M21 19V5a2 2 0 0 0-2-2h-4"/></>, download: <><path d="M12 3v12M7 10l5 5 5-5M5 21h14"/></>,
  };
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden>{p[name]}</svg>;
}
function Badge({ status }: { status: string }) { return <span className={`badge ${status.toLowerCase().replaceAll(" ", "-")}`}><i />{status}</span>; }

export default function Home() {
  const [session, setSession] = useState<Session | null>(null);
  const [view, setView] = useState("Overview");
  const [orders, setOrders] = useState(initialOrders);
  const [tickets, setTickets] = useState(initialTickets);
  const [toast, setToast] = useState("");
  const [showBroadcast, setShowBroadcast] = useState(false);
  const [showTicket, setShowTicket] = useState(false);
  const [selected, setSelected] = useState<Order | null>(null);
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { const saved = localStorage.getItem("xpack-session"); if (saved) setSession(JSON.parse(saved)); }, []);
  const message = (text: string) => { setToast(text); window.setTimeout(() => setToast(""), 3600); };
  const login = (next: Session) => { localStorage.setItem("xpack-session", JSON.stringify(next)); setSession(next); setView("Overview"); };
  const logout = () => { localStorage.removeItem("xpack-session"); setSession(null); setSelected(null); };
  const addOrder = (order: Order) => { setOrders([order, ...orders]); setShowBroadcast(false); message("Broadcast request submitted for review."); };
  const addTicket = (ticket: Ticket) => { setTickets([ticket, ...tickets]); setShowTicket(false); message("Support ticket created. Our team has been notified."); };
  const updateOrder = (id: string, status: Status, report = false) => { setOrders(orders.map(o => o.id === id ? { ...o, status, report: o.report || report } : o)); setSelected(null); message(status === "Completed" ? "Order completed and report shared with customer." : `Order updated to ${status}.`); };
  if (!session) return <Auth onLogin={login} />;
  const nav = session.role === "customer" ? [["Overview", "grid"], ["My broadcasts", "radio"], ["Support centre", "help"], ["Settings", "settings"]] : [["Overview", "grid"], ["Broadcast management", "radio"], ["Customers", "users"], ["Support desk", "help"], ["Activity log", "activity"]];
  return <main className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark"><b>x</b></span><span>Xpack</span></div><div className="workspace"><span className="company-dot">{session.role === "admin" ? "X" : session.name.slice(0, 1)}</span><span>{session.role === "admin" ? "Xpack Operations" : session.company || session.name}</span></div><nav>{nav.map(([label, icon]) => <button key={label} onClick={() => { setView(label); setSelected(null); }} className={view === label ? "active" : ""}><Icon name={icon as string}/>{label}</button>)}</nav><div className="sidebar-bottom"><div className="help-card"><span className="help-symbol">?</span><div><strong>Need help?</strong><p>Our team is here for you.</p><button onClick={() => setView(session.role === "admin" ? "Support desk" : "Support centre")}>Open support <Icon name="arrow" size={13}/></button></div></div><div className="user-card"><span className="avatar">{session.name.split(" ").map(x => x[0]).join("").slice(0,2)}</span><div><strong>{session.name}</strong><p>{session.role === "admin" ? "Xpack administrator" : "Customer account"}</p></div><button title="Sign out" onClick={logout}><Icon name="logout"/></button></div></div></aside><section className="content"><header><div className="mobile-brand">Xpack</div><div className="header-actions"><span className="access-label"><Icon name={session.role === "admin" ? "lock" : "users"} size={14}/>{session.role === "admin" ? "Admin access" : "Customer portal"}</span><button className="notification"><Icon name="bell"/><em>3</em></button><span className="header-avatar">{session.name.split(" ").map(x => x[0]).join("").slice(0,2)}</span></div></header><div className="page">{session.role === "customer" ? <CustomerPage view={view} orders={orders.filter(o => o.email === session.email)} tickets={tickets.filter(t => t.customer === (session.company || session.name))} setView={setView} create={() => setShowBroadcast(true)} ticket={() => setShowTicket(true)} select={setSelected} session={session} /> : <AdminPage view={view} orders={orders} tickets={tickets} setView={setView} select={setSelected} />}</div></section>{showBroadcast && <BroadcastModal onClose={() => setShowBroadcast(false)} onSubmit={addOrder} session={session}/>} {showTicket && <TicketModal onClose={() => setShowTicket(false)} onSubmit={addTicket} session={session}/>} {selected && <OrderModal order={selected} admin={session.role === "admin"} onClose={() => setSelected(null)} onUpdate={updateOrder}/>} {toast && <div className="toast"><span><Icon name="check" size={16}/></span>{toast}</div>}</main>;
}

function Auth({ onLogin }: { onLogin: (s: Session) => void }) {
  const [mode, setMode] = useState<"login" | "signup" | "admin" | "forgot">("login"); const [error, setError] = useState("");
  const submit = (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const data = new FormData(e.currentTarget); const email = String(data.get("email") || "").trim().toLowerCase(); const password = String(data.get("password") || ""); if (mode === "admin") { if (email !== ADMIN_EMAIL || password !== ADMIN_PASSWORD) return setError("Incorrect administrator username or password."); onLogin({ role: "admin", name: "Xpack Admin", email }); return; } if (mode === "forgot") { setError("If that email exists, a password reset link has been queued."); return; } const name = String(data.get("name") || "").trim(); const company = String(data.get("company") || "").trim(); if (mode === "signup" && (!name || password.length < 8 || password !== String(data.get("confirm") || ""))) return setError("Please complete all required fields and use matching 8+ character passwords."); onLogin({ role: "customer", name: mode === "signup" ? name : customerSeed.name, email: email || customerSeed.email, company: mode === "signup" ? company || name : customerSeed.company }); };
  const title = mode === "admin" ? "Administrator sign in" : mode === "signup" ? "Create your Xpack account" : mode === "forgot" ? "Reset your password" : "Welcome back";
  return <main className="auth-shell"><section className="auth-brand"><div className="brand"><span className="brand-mark"><b>x</b></span><span>Xpack</span></div><div><p className="eyebrow">IVR BROADCAST MANAGEMENT</p><h1>Every broadcast,<br/>clear and under control.</h1><p>Place orders, securely share files, track processing, and receive campaign reports in one focused workspace.</p></div><div className="auth-points"><span><Icon name="check"/>Secure file management</span><span><Icon name="check"/>Live order notifications</span><span><Icon name="check"/>Dedicated support desk</span></div></section><section className="auth-panel"><form className="auth-card" onSubmit={submit}><div className="auth-heading"><p className="eyebrow">{mode === "admin" ? "RESTRICTED AREA" : "XPACK PORTAL"}</p><h2>{title}</h2><p>{mode === "admin" ? "Use your authorized Xpack Operations credentials." : mode === "signup" ? "Set up your customer workspace in under a minute." : mode === "forgot" ? "We will email a secure reset link to you." : "Sign in to manage your broadcasts."}</p></div>{mode === "signup" && <><label>Full name<input name="name" required placeholder="Your full name"/></label><label>Company name <span>(optional)</span><input name="company" placeholder="Your company"/></label><label>Phone number<input name="phone" required placeholder="+91 00000 00000"/></label></>}<label>Email address<input name="email" type="email" required placeholder="you@company.com" defaultValue={mode === "admin" ? ADMIN_EMAIL : undefined}/></label>{mode !== "forgot" && <label>Password<input name="password" type="password" required minLength={8} placeholder="••••••••" defaultValue={mode === "admin" ? "" : undefined}/></label>}{mode === "signup" && <label>Confirm password<input name="confirm" type="password" required minLength={8} placeholder="••••••••"/></label>}{mode === "login" && <div className="auth-options"><label className="check"><input type="checkbox" defaultChecked/> Remember me</label><button type="button" onClick={() => { setMode("forgot"); setError(""); }}>Forgot password?</button></div>}{error && <p className="auth-error">{error}</p>}<button className="primary auth-submit">{mode === "signup" ? "Create account" : mode === "forgot" ? "Send reset link" : "Sign in"}<Icon name="arrow" size={16}/></button>{mode === "admin" ? <button type="button" className="plain-link" onClick={() => { setMode("login"); setError(""); }}>Back to customer sign in</button> : <><p className="auth-switch">{mode === "signup" ? "Already have an account?" : "New to Xpack?"} <button type="button" onClick={() => { setMode(mode === "signup" ? "login" : "signup"); setError(""); }}>{mode === "signup" ? "Sign in" : "Create an account"}</button></p><button type="button" className="admin-entry" onClick={() => { setMode("admin"); setError(""); }}><Icon name="lock" size={14}/>Administrator sign in</button></>}</form></section></main>;
}

function CustomerPage({ view, orders, tickets, setView, create, ticket, select, session }: { view: string; orders: Order[]; tickets: Ticket[]; setView: (v: string) => void; create: () => void; ticket: () => void; select: (o: Order) => void; session: Session }) {
  if (view === "My broadcasts") return <><Heading eyebrow="CUSTOMER PORTAL" title="My broadcasts" text="Every IVR broadcast request in one place." action="New broadcast" onAction={create}/><section className="panel data-panel"><OrderTable orders={orders} onSelect={select}/></section></>;
  if (view === "Support centre") return <><Heading eyebrow="SUPPORT CENTRE" title="How can we help?" text="Create a ticket and keep every conversation in one thread." action="New ticket" onAction={ticket}/><section className="support-layout"><section className="panel data-panel"><TicketTable tickets={tickets}/></section><aside className="panel support-aside"><Icon name="help" size={26}/><h2>Priority support</h2><p>Our operations team typically responds within one business day.</p><button className="outline" onClick={ticket}>Raise a ticket</button></aside></section></>;
  if (view === "Settings") return <><Heading eyebrow="ACCOUNT SETTINGS" title="Profile and preferences" text="Keep your account and notification preferences up to date."/><section className="panel settings-panel"><div className="setting-section"><h2>Profile information</h2><p>These details appear on your broadcast requests.</p><div className="form-grid"><label>Full name<input defaultValue={session.name}/></label><label>Company<input defaultValue={session.company}/></label><label>Email address<input defaultValue={session.email}/></label><label>Phone number<input placeholder="Add a phone number"/></label></div><button className="primary" onClick={() => alert("Profile changes are saved in the production database once connected.")}>Save changes</button></div><div className="setting-section"><h2>Notification preferences</h2><p>Receive an email when a broadcast changes status or a report is ready.</p><label className="toggle-row">Email status updates<input type="checkbox" defaultChecked/></label></div></section></>;
  const placed = orders.filter((o: Order) => o.status === "Placed").length, progressing = orders.filter((o: Order) => o.status === "In progress").length, completed = orders.filter((o: Order) => o.status === "Completed").length;
  return <><Heading eyebrow="CUSTOMER PORTAL" title={`Good morning, ${session.name.split(" ")[0]}`} text="Here’s what’s happening with your broadcasts." action="New broadcast" onAction={create}/><div className="metric-grid"><Metric icon="radio" label="Total broadcasts" value={orders.length} detail="All time"/><Metric icon="clock" label="Pending orders" value={placed} detail="Awaiting review" warning/><Metric icon="activity" label="In progress" value={progressing} detail="Being processed"/><Metric icon="chart" label="Completed" value={completed} detail="Reports ready" success/></div><div className="dashboard-grid"><section className="panel"><PanelTop title="Recent broadcasts" text="Your latest broadcast requests." action="View all" onAction={() => setView("My broadcasts")}/><OrderTable orders={orders.slice(0, 4)} onSelect={select}/></section><aside className="activity-panel panel"><PanelTop title="Recent activity" text="Across your account."/><div className="timeline"><Timeline color="blue" title="Broadcast submitted" text="Monsoon renewal reminder is awaiting review." time="Today, 10:42 AM"/><Timeline color="green" title="Report is ready" text="New product launch report was uploaded." time="Yesterday"/><Timeline color="red" title="Support ticket opened" text="Your request has been assigned to the team." time="Yesterday"/></div><button className="outline full" onClick={() => setView("Support centre")}>Open support centre</button></aside></div><section className="quick-section"><div><p className="eyebrow">QUICK ACTIONS</p><h2>Manage your broadcasts with ease</h2><p>Everything needed for a successful IVR campaign.</p></div><div className="quick-actions"><button onClick={create}><span className="icon-box blue"><Icon name="plus"/></span><span><strong>Create a broadcast</strong><small>Upload audio and contact list</small></span><Icon name="arrow" size={18}/></button><button onClick={() => setView("My broadcasts")}><span className="icon-box green"><Icon name="file"/></span><span><strong>View campaign reports</strong><small>Download completed results</small></span><Icon name="arrow" size={18}/></button></div></section></>;
}

function AdminPage({ view, orders, tickets, setView, select }: { view: string; orders: Order[]; tickets: Ticket[]; setView: (v: string) => void; select: (o: Order) => void }) {
  if (view === "Broadcast management") return <><Heading eyebrow="ADMIN PORTAL" title="Broadcast management" text="Review requests, access assets, and manage fulfillment."/><section className="panel data-panel"><div className="table-tools"><div className="search"><Icon name="search" size={16}/><input placeholder="Search order, customer, or reference"/></div><select><option>All statuses</option><option>Placed</option><option>In progress</option><option>Completed</option></select></div><OrderTable orders={orders} admin onSelect={select}/></section></>;
  if (view === "Customers") return <><Heading eyebrow="ADMIN PORTAL" title="Customer directory" text="Review customers, their activity, and account standing."/><section className="panel data-panel"><table><thead><tr><th>Customer</th><th>Email</th><th>Orders</th><th>Last activity</th><th>Account</th></tr></thead><tbody>{[...new Map<string, Order>(orders.map((o: Order): [string, Order] => [o.email, o])).values()].map((o: Order) => <tr key={o.email}><td><strong>{o.customer}</strong></td><td>{o.email}</td><td>{orders.filter((x: Order) => x.email === o.email).length}</td><td>{o.created}</td><td><Badge status="Active"/></td></tr>)}</tbody></table></section></>;
  if (view === "Support desk") return <><Heading eyebrow="ADMIN PORTAL" title="Support desk" text="Prioritize, reply to, and close customer conversations."/><section className="panel data-panel"><TicketTable tickets={tickets} admin/></section></>;
  if (view === "Activity log") return <><Heading eyebrow="ADMIN PORTAL" title="Activity log" text="A complete audit trail of operational activity."/><section className="panel activity-log"><Timeline color="blue" title="BR-1048 created" text="Dhruv Kumar & Co. submitted a new broadcast request." time="Today, 10:42 AM"/><Timeline color="green" title="Report uploaded" text="Admin completed BR-1046 and shared performance report." time="Yesterday, 4:22 PM"/><Timeline color="blue" title="Support ticket opened" text="Customer opened TK-208." time="Yesterday, 9:30 AM"/></section></>;
  const pending = orders.filter((o: Order) => o.status === "Placed").length, active = orders.filter((o: Order) => o.status === "In progress").length, done = orders.filter((o: Order) => o.status === "Completed").length;
  return <><Heading eyebrow="ADMIN PORTAL" title="Operations overview" text="A live view of your broadcast operations."/><div className="metric-grid"><Metric icon="users" label="Total customers" value={new Set(orders.map((o: Order) => o.email)).size} detail="Across all accounts"/><Metric icon="clock" label="Pending orders" value={pending} detail="Orders waiting for review" warning/><Metric icon="activity" label="In progress" value={active} detail="Currently processing"/><Metric icon="chart" label="Completed" value={done} detail="Reports delivered" success/></div><div className="dashboard-grid"><section className="panel urgent"><PanelTop title="Orders needing action" text="New requests and orders that need attention." action="Manage orders" onAction={() => setView("Broadcast management")}/><div className="urgent-list">{orders.filter((o: Order) => o.status !== "Completed").slice(0,3).map((o: Order, i: number) => <div className="urgent-row" key={o.id}><span className={`priority ${i === 0 ? "new" : "due-soon"}`}>{i === 0 ? "New" : "Due soon"}</span><div><strong>{o.id} · {o.customer}</strong><p>{o.contacts} contacts · {o.created}</p></div><button className="outline small" onClick={() => select(o)}>Review <Icon name="arrow" size={14}/></button></div>)}</div></section><aside className="panel queue"><PanelTop title="Support queue" text="Current ticket workload." action="Open desk" onAction={() => setView("Support desk")}/><div className="queue-stats"><div><b>{tickets.filter((t: Ticket) => t.status === "Open").length}</b><span>Open</span></div><div><b>{tickets.filter((t: Ticket) => t.status === "In progress").length}</b><span>In progress</span></div><div><b>{tickets.filter((t: Ticket) => t.status === "Resolved").length}</b><span>Resolved</span></div></div><div className="sla"><span className="icon-box red"><Icon name="clock"/></span><div><strong>2 tickets nearing SLA</strong><p>Respond within the next 2 hours.</p></div></div></aside></div><section className="panel operations"><PanelTop title="Today’s processing pipeline" text="Broadcast order health by status."/><div className="pipeline"><div><span className="pipe-number blue-fill">{pending}</span><strong>Placed</strong><p>Awaiting review</p></div><span className="pipe-line"/><div><span className="pipe-number yellow-fill">{active}</span><strong>In progress</strong><p>On IVR system</p></div><span className="pipe-line"/><div><span className="pipe-number green-fill">{done}</span><strong>Completed</strong><p>Reports delivered</p></div></div></section></>;
}

function Heading({ eyebrow, title, text, action, onAction }: { eyebrow: string; title: string; text: string; action?: string; onAction?: () => void }) { return <div className="page-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{text}</p></div>{action && <button className="primary" onClick={onAction}><Icon name="plus"/>{action}</button>}</div>; }
function PanelTop({ title, text, action, onAction }: { title: string; text: string; action?: string; onAction?: () => void }) { return <div className="panel-top"><div><h2>{title}</h2><p>{text}</p></div>{action && <button className="text-button" onClick={onAction}>{action}<Icon name="arrow" size={15}/></button>}</div>; }
function Metric({ icon, label, value, detail, warning, success }: { icon: string; label: string; value: number | string; detail: string; warning?: boolean; success?: boolean }) { return <article className="metric panel"><div className={`metric-icon ${warning ? "orange" : success ? "green" : "blue"}`}><Icon name={icon}/></div><p>{label}</p><h2>{value}</h2><small className={warning ? "warning-text" : success ? "success-text" : ""}>{detail}</small></article>; }
function Timeline({ color, title, text, time }: { color: string; title: string; text: string; time: string }) { return <div className="timeline-item"><span className={`timeline-dot ${color}`}><Icon name={color === "green" ? "chart" : color === "red" ? "help" : "activity"} size={13}/></span><div><strong>{title}</strong><p>{text}</p><small>{time}</small></div></div>; }
function OrderTable({ orders, onSelect, admin = false }: { orders: Order[]; onSelect: (o: Order) => void; admin?: boolean }) { return <div className="table-wrap"><table><thead><tr><th>Broadcast</th>{admin && <th>Customer</th>}<th>Created</th><th>Contacts</th><th>Status</th><th>Action</th></tr></thead><tbody>{orders.length ? orders.map(o => <tr key={o.id}><td><strong>{o.name}</strong><small>{o.id}</small></td>{admin && <td>{o.customer}</td>}<td>{o.created}</td><td>{o.contacts}</td><td><Badge status={o.status}/></td><td><button className="text-button row-text" onClick={() => onSelect(o)}>View</button></td></tr>) : <tr><td colSpan={admin ? 6 : 5} className="empty">No broadcast requests yet.</td></tr>}</tbody></table></div>; }
function TicketTable({ tickets, admin = false }: { tickets: Ticket[]; admin?: boolean }) { return <div className="table-wrap"><table><thead><tr><th>Ticket</th>{admin && <th>Customer</th>}<th>Priority</th><th>Status</th><th>Created</th></tr></thead><tbody>{tickets.map(t => <tr key={t.id}><td><strong>{t.subject}</strong><small>{t.id} · {t.message}</small></td>{admin && <td>{t.customer}</td>}<td><span className={t.priority === "High" ? "priority overdue" : "priority new"}>{t.priority}</span></td><td><Badge status={t.status}/></td><td>{t.created}</td></tr>)}</tbody></table></div>; }
function BroadcastModal({ onClose, onSubmit, session }: { onClose: () => void; onSubmit: (o: Order) => void; session: Session }) { const submit = (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const data = new FormData(e.currentTarget); const audio = data.get("audio") as File, contacts = data.get("contacts") as File; if (!audio?.name || !contacts?.name) return alert("Please attach both the MP3/WAV audio file and CSV/Excel contact list."); onSubmit({ id: `BR-${1050 + Math.floor(Math.random() * 850)}`, name: String(data.get("name")), customer: session.company || session.name, email: session.email, created: "Just now", contacts: "Pending validation", status: "Placed", schedule: String(data.get("schedule")), notes: String(data.get("notes") || "") }); }; return <div className="modal-backdrop" role="dialog" aria-modal="true"><form className="modal" onSubmit={submit}><div className="modal-head"><div><p className="eyebrow">NEW REQUEST</p><h2>Create a broadcast</h2><p>Upload your campaign assets for the Xpack operations team.</p></div><button type="button" className="close" onClick={onClose}><Icon name="close"/></button></div><label>Broadcast name<input name="name" required placeholder="e.g. August renewal reminder"/></label><div className="form-grid"><label>Audio file <span className="dropzone"><Icon name="upload"/><b>Upload MP3 or WAV</b><small>Maximum 25 MB</small><input name="audio" type="file" accept="audio/mpeg,audio/wav,.mp3,.wav" required/></span></label><label>Contact list <span className="dropzone"><Icon name="upload"/><b>Upload CSV or Excel</b><small>Maximum 50 MB</small><input name="contacts" type="file" accept=".csv,.xls,.xlsx" required/></span></label></div><label>Schedule<select name="schedule"><option>Start on processing</option><option>Schedule for later</option></select></label><label>Instructions <textarea name="notes" placeholder="Any instructions for our operations team?" rows={3}/></label><div className="modal-footer"><button type="button" className="outline" onClick={onClose}>Cancel</button><button className="primary">Submit broadcast <Icon name="arrow" size={16}/></button></div></form></div>; }
function TicketModal({ onClose, onSubmit, session }: { onClose: () => void; onSubmit: (t: Ticket) => void; session: Session }) { const submit = (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const d = new FormData(e.currentTarget); onSubmit({ id: `TK-${209 + Math.floor(Math.random() * 90)}`, subject: String(d.get("subject")), customer: session.company || session.name, priority: String(d.get("priority")) as "Normal" | "High", status: "Open", message: String(d.get("message")), created: "Just now" }); }; return <div className="modal-backdrop" role="dialog" aria-modal="true"><form className="modal compact-modal" onSubmit={submit}><div className="modal-head"><div><p className="eyebrow">SUPPORT</p><h2>New support ticket</h2><p>Describe your issue and we’ll get back to you.</p></div><button type="button" className="close" onClick={onClose}><Icon name="close"/></button></div><label>Subject<input name="subject" required placeholder="How can we help?"/></label><label>Priority<select name="priority"><option>Normal</option><option>High</option></select></label><label>Message<textarea name="message" required rows={5} placeholder="Give us the details…"/></label><div className="modal-footer"><button type="button" className="outline" onClick={onClose}>Cancel</button><button className="primary">Create ticket <Icon name="arrow" size={16}/></button></div></form></div>; }
function OrderModal({ order, admin, onClose, onUpdate }: { order: Order; admin: boolean; onClose: () => void; onUpdate: (id: string, s: Status, report?: boolean) => void }) { const [status, setStatus] = useState<Status>(order.status); return <div className="modal-backdrop" role="dialog" aria-modal="true"><div className="modal compact-modal"><div className="modal-head"><div><p className="eyebrow">{order.id}</p><h2>{order.name}</h2><p>{order.customer} · {order.contacts} contacts</p></div><button className="close" onClick={onClose}><Icon name="close"/></button></div><div className="detail-grid"><div><small>Current status</small><Badge status={order.status}/></div><div><small>Schedule</small><strong>{order.schedule}</strong></div><div><small>Audio asset</small><button className="text-button"><Icon name="download" size={14}/>Download MP3</button></div><div><small>Contact list</small><button className="text-button"><Icon name="download" size={14}/>Download CSV</button></div></div>{order.notes && <div className="detail-note"><strong>Customer instructions</strong><p>{order.notes}</p></div>}{order.report && <div className="report-ready"><Icon name="check"/><div><strong>Performance report ready</strong><p>Report has been uploaded to this order.</p></div><button className="outline"><Icon name="download" size={14}/>Download</button></div>}{admin && <div className="admin-update"><label>Update order status<select value={status} onChange={e => setStatus(e.target.value as Status)}><option>Placed</option><option>In progress</option><option>Completed</option><option>Cancelled</option></select></label>{status === "Completed" && <label>Performance report<input type="file" accept=".csv,.pdf,.zip"/></label>}<button className="primary" onClick={() => onUpdate(order.id, status, status === "Completed")}>Save update</button></div>}<div className="modal-footer"><button className="outline" onClick={onClose}>Close</button></div></div></div>; }
